# Site settings
github: [metadata]
title: AcklenAvenue-Website
email: info@acklenavenue.com
description: >
 Your partner in building powerful apps users love, Acklen Avenue offers agile software development teams as a service.

url: "http://acklenavenue.com"
twitter_username: acklenavenue
exclude: ['README.md']

# Build settings
environment: production
gems:
  - jekyll-gist
markdown: kramdown
permalink: /articles/:title
source: .
destination: ./_site
permalink: /:title

development:
  app_url: "http://localhost:4000/"


