# Site settings
github: [metadata]
title: AcklenAvenue-Website
email: info@acklenavenue.com
description: >
  Acklen Avenue is a leading custom software development in Nashville, Tennessee. 
  Our talented team is passionate about clean code and simple user experience.

url: "http://acklenavenue.com"
twitter_username: acklenavenue
exclude: ['README.md']

# Build settings
environment: production
plugins:
  - jekyll-gist
  - jekyll-redirect-from
markdown: kramdown
permalink: /articles/:title
source: .
destination: ./_site
permalink: /:title

development:
  app_url: "http://localhost:4000/"

exclude: ['badges']

# Collections settings
collections:
  job_openings:
    output: true
    permalink: careers/:title
  posts:
    output: true
    permalink: blog/:title